version: '3.9'

services:
  modev-backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    platform: linux/amd64
    container_name: modev-backend
    ports:
      - "8080:8080"
    environment:
      - "ENV=local"
      - "DB_HOST=mysql"
      - "DB_USER=user"
      - "DB_PASSWORD=password"
    volumes:
      - ./:/go/src/github.com/originbenntou/modev-backend
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.33
    container_name: modev-mysql
    platform: linux/amd64
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./data-volume:/var/lib/mysql

volumes:
  data-volume:

networks:
  default:
    name: modev-backend-network
