openapi: 3.0.3
info:
  title: modev-backend
  description: |-
    MoDev API schema
  contact:
    email: originbenntou@gmail.com
  version: 0.0.1
servers:
  - url: https://api.mototsuka.com/
tags:
  - name: tweets
paths:
  /tweets:
    get:
      tags:
        - tweets
      operationId: tweets
      parameters:
        - name: category
          in: query
          required: true
          schema:
            type: string
            default: like
            enum:
              - like
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tweets'
        '400':
          description: Invalid parameters

components:
  schemas:
    Tweets:
      required:
        - id
        - addDate
        - url
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        addDate:
          type: string
          example: 1999-01-01
        url:
          type: string
          example: https://example.com
        tags:
          type: array
          items:
            type: string
          example: [ "Cat", "Pretty", "Small" ]
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
